# Generated by Django 5.2.10 on 2026-01-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_studied', models.IntegerField()),
                ('previous_scores', models.IntegerField()),
                ('extracurricular', models.BooleanField()),
                ('sleep_hours', models.IntegerField()),
                ('sample_papers', models.IntegerField()),
                ('performance_index', models.FloatField()),
            ],
        ),
    ]
