# Generated by Django 6.0.1 on 2026-02-09 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentperformance',
            name='extracurricular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='hours_studied',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(16)]),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='previous_scores',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='sample_papers',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='sleep_hours',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
